### ISSUE TITLE
[KeyvAdapter] Allow return "undefined" when cache backend is unavailable

### ISSUE THREAD

**Issue by PhantomRay** [apollographql/apollo-utils#211]
I am using `@apollo/utils.keyvadapter` to implement redis cache backend. The adapter makes redis or other cache backend a hard dependency. This means when the apollo server lost connection to redis server, any incoming requests will fail. It would be good to allow the redis client to retry connection. At the same time, any queries with cache control should still function by bypassing cache.

Meanwhile, I use the following code to achieve the goal.
```js
class BetterKeyvAdapter extends KeyvAdapter {
  // this will allow the query to bypass the cache if cache backend is not available
  async get(key) {
    try {
      return await super.get(key);
    } catch (e) {
      return undefined;
    }
  }
}
```

**Comment by glasser** [comment]
It looks like you're looking for `ErrorsAreMissesCache`, a KeyValueCache implementation that wraps another KeyValueCache implementation. It is provided by [`@apollo/utils.keyvaluecache`](https://www.npmjs.com/package/@apollo/utils.keyvaluecache).
