### ISSUE TITLE
keyvAdapter: support Keyv 5

### ISSUE THREAD

**Issue by goto-bus-stop** [apollographql/apollo-utils#457]
Keyv 5 was released today. <strike>It appears to have [some issues](https://github.com/jaredwray/keyv/issues/1113), but once resolved</strike> It would be nice to support the new version.

Someone tried it already and got this type error: https://github.com/jaredwray/keyv/issues/1113#issuecomment-2301217699

**Comment by jaredwray** [comment]
@goto-bus-stop - you should be able to get this working now with `v5.0.1`

**Comment by reggermont** [comment]
Different project, but yes it seems to work on my side

Therefore typing doesn't seem up-to-date, here's the related ticket: https://github.com/apollographql/apollo-utils/issues/459
