### ISSUE TITLE
Package READMEs

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/apollo-utils#69]
Introduce READMEs for each package

Update directory in package.json files, maybe that fixes the reference / homepage link on npmjs website.

**Comment by Tanner-Scadden** [comment]
Is this package still being supported? I am having troubles getting this package to cache properly. I do exactly what the docs currently say to do but redis stays empty and there aren't any errors. I don't believe it's a redis issue since I use keyv for external API integrations and that populates redis correctly. Would love to see more information about this package to debug the issue!

**Comment by trevor-scheer** [comment]
@Tanner-Scadden I'm not sure how this issue pertains to yours. Can you please open a separate issue with a runnable reproduction of the issue you're seeing? A good reproduction should require no creativity on my end - ideally a sandbox or something I can `git clone` and run locally.

Also I assume you're talking about `@apollo/utils.keyvadapter` but this repo is home to a number of packages, so please clarify in the issue you open.

**Comment by Tanner-Scadden** [comment]
> @Tanner-Scadden I'm not sure how this issue pertains to yours. Can you please open a separate issue with a runnable reproduction of the issue you're seeing? A good reproduction should require no creativity on my end - ideally a sandbox or something I can `git clone` and run locally.
> 
> Also I assume you're talking about `@apollo/utils.keyvadapter` but this repo is home to a number of packages, so please clarify in the issue you open.

Sure, I can create a new issue. The reason why I commented it on here is I'm sure that I am just missing something in the set up phase of it that would be resolved through more documentation on how to use the adapter. Sorry if this was not the right place. Yes, I am talking about @apollo/utils.keyvadapter. I'll set up an example.
